export const defaultChartTypes: Record<string, string> = {
  'Totales Generales de Venta': 'Barra',
  'Promedio Diario de Venta': 'Barra',
  'Totales Generales de Utilidad': 'Barra',
  'Promedio Diario de Utilidad': 'Torta',
  'Totales Generales de Valor Ticket de Venta': 'Barra',
  'Promedio Diario de Valor Ticket de Venta': 'Barra',
  'Totales Generales de Costos de Venta': 'Torta',
  'Promedio Diario de Costos de Venta': 'Barra',
  'Totales Generales de Porcentaje de Utilidad': 'Torta',
  'Promedio Diario de Porcentaje de Utilidad': 'Torta',
  'Promedio Diario de Margen de Ganancia': 'Torta',
  'Totales Generales de Unidades Vendidas': 'Barra',
  'Promedio Diario de Unidades Vendidas': 'Barra',
  'Totales Generales de Facturas Emitidas': 'Torta',
  'Promedio Diario de Facturas Emitidas': 'Torta',
  'Totales Generales de Unidades en Bolsa': 'Torta',
  'Promedio Diario de Unidades en Bolsa': 'Torta',
  'Totales Generales de Valor Promedio de la Unidad': 'Torta',
  'Promedio Diario de Valor Promedio de la Unidad': 'Torta',
  'Totales Generales de Clientes Atendidos': 'Torta',
  'Promedio Diario de Clientes Atendidos': 'Torta',
  'Totales Generales de Clientes Frecuentes': 'Torta',
  'Promedio Diario de Clientes Frecuentes': 'Torta',
  'Totales Generales de Clientes Nuevos': 'Torta',
  'Promedio Diario de Clientes Nuevos': 'Torta',
  'Día más Exitoso': 'Línea',
  'Venta más Exitosa': 'Línea',
  'Ranking de 5 Operadores más Productivos': 'Barra',
  'Ranking de 5 Fabricantes más Vendidos': 'Barra',
}